# Generated by Django 3.1.7 on 2021-08-29 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default=datetime.datetime(2021, 8, 29, 16, 27, 54, 889918, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
