# Generated by Django 3.2.6 on 2021-08-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_student_number', models.CharField(max_length=50)),
                ('resident_name', models.CharField(max_length=50)),
                ('resident_surname', models.CharField(max_length=50)),
                ('visitor_identity', models.CharField(max_length=50)),
                ('visitor_name', models.CharField(max_length=50)),
                ('visitor_surname', models.CharField(max_length=50)),
                ('date_and_time_in', models.DateTimeField()),
                ('date_and_time_out', models.DateTimeField()),
            ],
        ),
    ]
