# Generated by Django 3.1.7 on 2021-08-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_register', '0002_alter_visitors_resident_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
