# Generated by Django 3.1.7 on 2021-08-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_register', '0004_auto_20210829_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='visitors',
            new_name='Visitor',
        ),
    ]
